### ISSUE TITLE
Request for License/Permission to Use Code

### ISSUE THREAD

**Issue by DarylRyanChong** [hocop/binary-autoencoder#1]
Hi Ruslan,

Thanks for sharing the code for this project! My name is Daryl, and I work at Qunova Computing. I recently came across your GitHub repo for the bVAE and we're considering using it as part of a product we’re developing.

I noticed there’s no license attached, so I just wanted to check if you’d be okay with us using and modifying it for commercial purposes. If you’re open to it, would you be able to add a license like MIT or Apache 2.0 to the repo?

I really appreciate the work you’ve done, and we’d be happy to credit you if we move forward with it. Thanks so much for your time!

Best,

Daryl Ryan Chong

**Comment by hocop** [comment]
Hi Daryl!

Added MIT license. Please do what you like with the code :)
